package(default_visibility = ["//:internal"])

load("//:defs.bzl", "gs_ui")

gs_ui(
    deps = [
      "@gs_tools//src",
      "//src/common",
      "//src/const",
      "//src/theming",
      "//src/tool",
    ])