package(default_visibility = ["//:internal"])

load("//:defs.bzl", "gs_ui")

gs_ui(
    deps = [
      "@gs_tools//src",
      "//src/button",
      "//src/input",
      "//src/section",
      "//src/routing",
      "//src/theming",
      "//src/tool",
    ])
